
FROM ghcr.io/ggml-org/llama.cpp:server-cuda

EXPOSE 8000

COPY docker-ia-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-ia-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-ia-entrypoint.sh"]