services:
  node_angular:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    # network_mode: service:ia
  ia:
    build:
      context: .
      dockerfile: Dockerfile.ia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - '8000:8000'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - models_data:/models

volumes:
  models_data:
    external: true
